### PR TITLE
Fixed bad event names in README

### PR DESCRIPTION
**Pull request by evillemez**

### CODE REVIEW

**Comment by DavidMikeSimon** [comment]
Cool, just a docs update then?

**Comment by evillemez** [comment]
Yeah, just docs... Spent a lot of time trying to figure out why my listeners weren't being called.

There's more I want to do to this thing, but no time right now :/
- Evan

**Comment by nesretepk** [comment]
Nice to see you in here, Evan...

**Comment by evillemez** [comment]
Indeed :)

**Pull request merged**
